### ISSUE TITLE
Create parser for UI input into DLX parameters

### ISSUE THREAD

**Issue by jbukhari** [dag-hammarskjold-library/itp-process#22]
This could be a function or class, perhaps as part of a utilities module. Or it could just be coded into the route. TBD

**Comment by aaronhelton** [comment]
I think this is related to #24

**Comment by Yalshire2004** [comment]
part of the issue #35

**Comment by jbukhari** [comment]
This is what I will be doing to get the arguments from `requests.args` to `dlx.match()`
