### ISSUE TITLE
Create storage mechanism for rules, etc.

### ISSUE THREAD

**Issue by jbukhari** [dag-hammarskjold-library/itp-process#23]
Possible usage: `rule.store()` where `rule` is a Rule object and `store()` is a method defined in the Rule class. TBD.

**Comment by aaronhelton** [comment]
Take a look at https://github.com/dag-hammarskjold-library/itp-process/blob/routes/app/models.py

**Comment by aaronhelton** [comment]
This is almost a duplicate of #24

**Comment by aaronhelton** [comment]
This is completed
