### ISSUE TITLE
Create routes for validation reports

### ISSUE THREAD

**Issue by aaronhelton** [dag-hammarskjold-library/itp-process#26]
We need to define and create routes for the validation reports. For instance:

`/<body>/<session>`

might bring up a list of the validation reports available for that body/session combo

and 

`/<body>/<session>/missing_field/<field>`

would bring up the validation report for the body/session and field combination

Other schemes are possible

**Comment by aaronhelton** [comment]
There are basic routes for these, but they are not yet connected to a model.

**Comment by Yalshire2004** [comment]
Proposal for the route namming :
/reports/<name of the report family>/<list of tag defining the parameters>
e.g : Missing field report:
/reports/<name of the report family>/<tag>/<authority ID>
Explanations :
<name of the report family> : family of the report (Missing reports,Duplicate records,Subfield comparison).
<tag> : Regarding the missing field report, it should be the field number (e.g 930) to query.

**Comment by Yalshire2004** [comment]
Proposal for the route namming :
/reports/<name of the report family>/<list of tag defining the parameters>
e.g : Missing field report:
/reports/<name of the report family>/<tag>/<authority ID>
Explanations :
(<name of the report family>) : family of the report (Missing reports,Duplicate records,Subfield comparison).
(<tag>) : Regarding the missing field report, it should be the field number (e.g 930) to query.

**Comment by Yalshire2004** [comment]
Proposal for the route namming :
/reports/name of the report family/list of tag defining the parameters
e.g : Missing field report:
/reports/name of the report family/tag/authority ID
Explanations :
(name of the report family) : family of the report (Missing reports,Duplicate records,Subfield comparison).
(tag) : Regarding the missing field report, it should be the field number (e.g 930) to query.
