### ISSUE TITLE
provide record_id on exception when generating sections

### ISSUE THREAD

**Issue by grozdanic** [dag-hammarskjold-library/itp-process#347]
The generic message that pops up when generating section for E/2022-S itpsubj : $concat only supports strings, not array, full error: {'ok': 0.0, 'errmsg': '$concat only supports strings, not array', 'code': 16702, 'codeName': 'Location16702'}. 

The message should indicate a record_id of the record with the data condition that throws an exception.

**Comment by wernerval** [comment]
I have now installed read-access to Mongo DB. Bojan explained to me how to navigate MongoDB in order to be able to find the record/s that could potentially block the output of a section.
Therefore, this ticket is now closed.
