### ISSUE TITLE
Timeout issues when generating snapshots

### ISSUE THREAD

**Issue by JoelleSciboz** [dag-hammarskjold-library/itp-process#348]
For large snapshots (i.e. GA snapshots) the application timeout and the snapshot is not generated. Solution suggested by Bojan is to move the application out of Lamda to ...

**Comment by grozdanic** [comment]
.. to EC2. We will need to adjust the application slightly to ensure that it doesn't initiate another asynch job, and instead that it runs in the foreground.

**Comment by wernerval** [comment]
Resolved.
