### ISSUE TITLE
11th emergency special sess. - No data output for ITS corporate

### ISSUE THREAD

**Issue by wernerval** [dag-hammarskjold-library/itp-process#349]
Index to Speeches - corporate

Snapshot (325 ITS records), section and word document generated successfully.
However, the Word document has no data, it is blank.

<img width="325" alt="Screen Shot 2022-10-14 at 2 01 43 PM" src="https://user-images.githubusercontent.com/115169780/195912137-27a42230-9899-41e8-aec4-19445e46a96e.png">

[A11emsp-itpitsc-1665770246 (1).docx](https://github.com/dag-hammarskjold-library/itp-process/files/9788966/A11emsp-itpitsc-1665770246.1.docx)

**Comment by grozdanic** [comment]
This works fine. The section for itsc was not generated previously.

**Comment by wernerval** [comment]
Great!
Thank you.
