### ISSUE TITLE
Adjust comparison tool - SC (X27 code related)

### ISSUE THREAD

**Issue by wernerval** [dag-hammarskjold-library/itp-process#352]
Issue was first reported on 3 October 2022.

Eric fixed the duplicate data in the Subject Index of the SC (related to the code X27 in records). 
At the database level, the duplicates are still there. It was implemented a workaround acting on the rendering of the word document.

**Duplicates should be eliminated at the data source.**
While running the comparison tool of the SC, it throws too many results and then the text is not aligned and becomes inefficient the comparison itself.

See example below:
S/75
CENTRAL AFRICAN REPUBLIC SITUATION
![image](https://user-images.githubusercontent.com/115169780/196530469-85374bd7-2a75-4040-b952-45bb983134e7.png)

**Comment by grozdanic** [comment]
Can you please include the text file to compare? I need to replicate the issue..
Snapshots would not duplicate data from Hz.
Attached are the 5 records with 791__a:"S/PV.8728"

[SPV8728.csv](https://github.com/dag-hammarskjold-library/itp-process/files/9821393/SPV8728.csv)

**Comment by wernerval** [comment]
The attached records that you've provided are for the Index to Speeches.
My request relates to the Subject Index. Please discuss with Eric that he is familiar with the issue

**Comment by grozdanic** [comment]
closing this issue as resolved

**Comment by wernerval** [comment]
Resolved. Thank you!
