### ISSUE TITLE
Change extraction of speech records - records are not showing-up

### ISSUE THREAD

**Issue by wernerval** [dag-hammarskjold-library/itp-process#353]
Issue was first reported on 29 August 2022.

Code should be changed to extract speech records following the same instruction as the old scripts:
- Go through each record and Check to see if 035$a starts with a Q 
If not, exit process and proceed to the next record.

The new app is extracting the speech records using 930 "ITS".
It was discovered that speech records were not showing-up due to data entry problems (other values than ITS, extra spacing, etc.). The 035 field is more stable and not prone to data entry issues, therefore, we will ensure that all speech records are included.

Examples found running the comparison tool (please note that these records have been fixed already). The examples are provided to show how following the old script instruction ensures a more precise output:

A/65 ITS (itpits) (highlighted those that are not showing in the new app):
![image](https://user-images.githubusercontent.com/115169780/196535906-e0eee128-7cf3-4435-8879-d529ff27ad16.png)

**old script**

_**POVERTY–INTERNATIONAL DECADE (2008-2017) (Agenda item 24a) 

**Kleib, Hasan (Indonesia) – [A/C.2/65/SR.2](http://undocs.org/A/C.2/65/SR.2)** 

Saripudin, Mohamed Hery (Indonesia) – [A/C.2/65/SR.16](http://undocs.org/A/C.2/65/SR.16)**_ 

**new script**

_**POVERTY—INTERNATIONAL DECADE (2008-2017) (Agenda item 24a) 

Saripudin, Mohamed Hery (Indonesia) - [A/C.2/65/SR.16](https://undocs.org/A/C.2/65/SR.16)**_

**Comment by grozdanic** [comment]
maybe check this UNDL query to detect inconsistencies with 930.a:

035:/^Q/ AND 791__b:"A/" AND 791__c:"70" AND NOT 930__a:[ITS]

similarly, other unwanted conditions could be detected as well in UNDL.

I would need to reproduce the condition and know about the expected results to be able to know for sure if the upcoming change works as expected.

**Comment by wernerval** [comment]
I also just discovered that the practice to include 930 ITS, started around 2003 (GA, 58th session).
So older records will not work with the query in place in the new app.
