### ISSUE TITLE
Validation report - Bib report - New - Find 515 and 520 does not end with a period

### ISSUE THREAD

**Issue by wernerval** [dag-hammarskjold-library/itp-process#375]
Issue was first reported on 11 May 2022.

The old script would add a period at the end of the 515 and 520 fields (if not present in the record).
The new ITPP doesn't, because we want to add the period in the record if needed (5xx fields end with a period).

The validation report will find those bib records where fields 515 and 520 do not end with a period.

Should be inserted here:
<img width="289" alt="image" src="https://user-images.githubusercontent.com/115169780/224414924-69c96e6d-9571-448a-b508-0cc3d10a77c8.png">

**Comment by grozdanic** [comment]
Can you use the query **515__a:/^[^.]*$/** in Metadata Editor for this purpose?

**Comment by wernerval** [comment]
It does work but I think I will query in the UNDL instead, so I can narrow the collection (organ and session).

If we do not add it as validation report, would it be possible that I can add the query as a **link** in the Bib reports list?

So not only I could add this query to the list but others as well (so the page will serve also as a check-list of the queries I have to do before editing).
If I have access to this page, I could add it myself...

Example:
<img width="363" alt="image" src="https://user-images.githubusercontent.com/115169780/229582574-1273d8d9-8c6e-49d4-9402-c23ae13bee01.png">

**Comment by wernerval** [comment]
1.Could you please replace the second subtitle to match? https://vrjd5z6e2e.execute-api.us-east-1.amazonaws.com/dev/reports/bib_ending_with_period_515_520
515 or 520 not ending with a period
(right now it says "Bibs with 515 or 520 repeated")
<img width="860" alt="image" src="https://github.com/dag-hammarskjold-library/itp-process/assets/115169780/1f7992aa-4462-4774-abf7-2b6d92783043">


2. Could you please list it after "Duplicate 515 and 520"?
https://vrjd5z6e2e.execute-api.us-east-1.amazonaws.com/dev/

<img width="266" alt="image" src="https://github.com/dag-hammarskjold-library/itp-process/assets/115169780/03c8daa3-91ad-4b7c-a77c-de8cdfbd8963">

**Comment by wernerval** [comment]
Please see my comment on the ticket.

Thank you!

___

Ms. Valeria Werner
Editor, Dag Hammarskjöld Library
1-917-367-2173
***@***.******@***.***>

United Nations
New York | Room L-0213C
Index to Proceedings<https://www.un.org/en/library/page/index-proceedings> – Index to Speeches<https://www.un.org/library/page/speeches-and-meetings>
UN Digital Library<https://digitallibrary.un.org/>

From: jbukhari ***@***.***>
Reply-To: dag-hammarskjold-library/itp-process ***@***.***>
Date: Monday, May 15, 2023 at 12:05 PM
To: dag-hammarskjold-library/itp-process ***@***.***>
Cc: Valeria Werner ***@***.***>, Author ***@***.***>
Subject: Re: [dag-hammarskjold-library/itp-process] Validation report - Bib report - New - Find 515 and 520 does not end with a period (Issue #375)


Closed #375<https://github.com/dag-hammarskjold-library/itp-process/issues/375> as completed via #405<https://github.com/dag-hammarskjold-library/itp-process/pull/405>.
