### ISSUE TITLE
S/78 - itpitsp - unable to generate Word doc.

### ISSUE THREAD

**Issue by wernerval** [dag-hammarskjold-library/itp-process#396]
The S/78 itpitsp (speakers) is not showing up in the List of Generated Word docs. (I do not get any error messages through the process):
[https://vrjd5z6e2e.execute-api.us-east-1.amazonaws.com/dev/files](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvrjd5z6e2e.execute-api.us-east-1.amazonaws.com%2Fdev%2Ffiles&data=05%7C01%7Cwernerv%40un.org%7C207dad6b67914845505c08db467ce5ce%7C0f9e35db544f4f60bdcc5ea416e6dc70%7C0%7C0%7C638181274456754946%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OgNqn7ZFZsHxQ9Korqe3BmVKTVde3gxJG9B9SY%2Bp1JA%3D&reserved=0)
 
I was able to generate the A/77 though.
 
Do you know what could be preventing it from showing-up in the list?

**Comment by grozdanic** [comment]
it looks like the reason is that there were more than 1000 generated files.
Could we delete older files, say from 2022 to free up space/reduce the number of files on s3?

**Comment by wernerval** [comment]
Yes, sure, please do so (we were actually discussing deleting files with Eric today in a non-related discussion).
thank you

**Comment by grozdanic** [comment]
It is done! I left only docx and mrc files generated in 2023
