### ISSUE TITLE
Unable to generate itpsubj section - S/67

### ISSUE THREAD

**Issue by wernerval** [dag-hammarskjold-library/itp-process#400]
While trying to generate the itpsubj for S/67 in:
https://vrjd5z6e2e.execute-api.us-east-1.amazonaws.com/dev/itp/selectSection/

I get the following error message:
•	PlanExecutor error during aggregation :: caused by :: $split requires an expression that evaluates to a string as a first argument, found: array, full error: {'ok': 0.0, 'errmsg': 'PlanExecutor error during aggregation :: caused by :: $split requires an expression that evaluates to a string as a first argument, found: array', 'code': 40085, 'codeName': 'Location40085', '$clusterTime': {'clusterTime': Timestamp(1683593931, 1), 'signature': {'hash': b'`0\\\xb7\x03i\xa9\xb2\x11Un`VR\x97j\xcc\xbd=\x89', 'keyId': 7196005730632073221}}, 'operationTime': Timestamp(1683593931, 1)}

**Comment by grozdanic** [comment]
Can you check highlighted records in this csv; looks like they have multiple 992 dates..and it could be the reason for the error..
[itpp_snapshot_test3.csv](https://github.com/dag-hammarskjold-library/itp-process/files/11433895/itpp_snapshot_test3.csv)

**Comment by wernerval** [comment]
Thank you Bojan, yes, those were the problem records. Viola updated the records and now I can generate the section.
Thank you!
