### ISSUE TITLE
Time out management

### ISSUE THREAD

**Issue by Yalshire2004** [dag-hammarskjold-library/itp-process#44]
Is it possible to avoid the timeout mail sent by the server implementing a try/catch ?

**Comment by jbukhari** [comment]
I have an idea involving putting a timer in the report execution method, to kill the function if it exceeds 30 seconds. It could then return an error message to the user before API gateway times out.

**Comment by jbukhari** [comment]
This would probably do the trick https://docs.python.org/3/library/asyncio-task.html#timeouts

**Comment by Yalshire2004** [comment]
I was thinking about this afternoon.... This one could help :  https://stackoverflow.com/questions/492519/timeout-on-a-function-call

⁣Télécharger BlueMail pour Android ​

Le 9 oct. 2019 à 17:14, à 17:14, jbukhari <notifications@github.com> a écrit:
